import scrapy

class MarketItem(scrapy.Item):
    external_id = scrapy.Field()
    name = scrapy.Field()
    municipality = scrapy.Field()
    category = scrapy.Field()
    start_date = scrapy.Field()
    end_date = scrapy.Field()
    address = scrapy.Field()
    city = scrapy.Field()
    postal_code = scrapy.Field()
    latitude = scrapy.Field()
    longitude = scrapy.Field()
    description = scrapy.Field()
    organizer_name = scrapy.Field()
    organizer_phone = scrapy.Field()
    organizer_email = scrapy.Field()
    organizer_website = scrapy.Field()
    opening_hours = scrapy.Field()
    entry_fee = scrapy.Field()
    stall_count = scrapy.Field()
    has_food = scrapy.Field()
    has_parking = scrapy.Field()
    has_toilets = scrapy.Field()
    has_wifi = scrapy.Field()
    is_indoor = scrapy.Field()
    is_outdoor = scrapy.Field()
    special_features = scrapy.Field()
    source_url = scrapy.Field()
    loppemarkeder_nu = scrapy.Field()  # raw JSON metadata for loppemarkeder.nu
    scraped_at = scrapy.Field()
